### ISSUE TITLE
Context naming

### ISSUE THREAD

**Issue by ciaranmcnulty** [Sam-Burns/psr7-symfony-httpfoundation#2]
I don't believe `BlackBoxContext` vs `WhiteBoxContext` are correct naming; in both cases you're doing black box testing, you're just testing with different levels of infrastructure.

I would suggest `RequestContext` and `WebContext` or something similar.

To be honest I'm not sure your blackbox test is adding any value to the suite aside from complexity; I'd be happy with just the white box layer but YMMV. Certainly if you retain the complete webserver test it should be restricted to one scenario.

**Comment by Sam-Burns** [comment]
I have renamed the contexts as suggested, and restricted the webserver context to a single scenario.

I am keen to keep the webserver context in there for now, as it is currently the only test in an entire HTTP Request/Response library that touches an actual HTTP Request or Response.
