### ISSUE TITLE
Use without Symfony request

### ISSUE THREAD

**Issue by ciaranmcnulty** [Sam-Burns/psr7-symfony-httpfoundation#3]
Currently the SF2 request is optional in the constructor.

This should be removed; it will be easier to focus on being an adaptor layer if we do not try and _also_ make it a generic PSR-7 implementation too.

**Comment by Sam-Burns** [comment]
Fixed by [91d0aa87d316ee1b8c19f33b3510d4e7565c1623](http://github.com/Sam-Burns/psr7-symfony-httpfoundation/commit/91d0aa87d316ee1b8c19f33b3510d4e7565c1623)
