### ISSUE TITLE
Deprecate this library in favor of the official Symfony PSR-7 adapter

### ISSUE THREAD

**Issue by stof** [Sam-Burns/psr7-symfony-httpfoundation#5]
Hi,

The Symfony core team is already working on its plan for an adapter between PSR-7 and HttpFoundation. We took our decision a few minutes ago and we will announce it very soon.
We decided to use a different approach than yours (allowing a 2-ways adapter which allows for much more use cases than your implementation). The work will happen in https://github.com/symfony/psr-http-message-bridge (the implementation has not yet started though).
So I'm not sure dedicating more time to this PSR-7 implementation is actually worth it.

**Comment by Sam-Burns** [comment]
I'm sorry, this really isn't a bug.

**Comment by stof** [comment]
Well, I know it is not a bug. I was a way to start the discussion

**Comment by vitorbrandao** [comment]
Thanks @stof for your update. OSS is about diversity but also about focusing our resources on promising  projects. Keeping https://github.com/symfony/psr-http-message-bridge under my radar. And thanks @Sam-Burns also for kickstarting this.

**Comment by ciaranmcnulty** [comment]
@stof TBH even though eventually the symfony component likely be used more widely, it's a little rude to post issues to other projects suggesting they abandon their efforts because you've created an empty repository.

IMO it remains to be seen what approach the symfony component will use. It sounds like it'll be different  to @Sam-Burns's approach of making an Adapter so there's no reason the two can't coexist.

**Comment by vitorbrandao** [comment]
Maybe a constructive discussion in the sf mailing list comparing both approaches would be useful. /cc @Sam-Burns, @stof.

If not, this is OSS, nothing stops contributors to keep working on their projects.

**Comment by stof** [comment]
@ciaranmcnulty the fact is that this repository does not contain a working implementation either. This is why I wanted to initiate the discussion sooner rather than later. And the approach used here does not allow to create middleware adapters, as you will need to convert the Request and the Response in opposite ways for that, and this is a 1-way adapter only with this approach.

However, I recognize that the wording of my initial comment might have been better. Sorry about that.
